# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [58]:
# Creating arrays
a = np.zeros((3))
#print a
b = np.ones((2,3))
#print b
c = np.random.randint(1,10,(2,3,4))
print c
d = np.arange(0,10,1).reshape((2,5))
print d

[[[3 7 4 8]
  [2 8 5 2]
  [3 7 9 2]]

 [[4 9 7 9]
  [5 4 3 4]
  [1 5 3 9]]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


What are these functions?

    arange?

In [ ]:
# Note the way each array is printed:
a,b,c,d

In [ ]:
## Arithmetic in arrays is element wise

In [59]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [61]:
c = a-b
c


array([20, 29, 38, 47])

In [60]:
b**2

array([0, 1, 4, 9])

## Indexing, Slicing and Iterating

In [62]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [63]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [64]:
a[2:5]

array([ 4,  9, 16])

In [ ]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [66]:
b = np.random.randint(1,100,(4,4))

In [77]:
print b
print b.T

[[33 52 41 94]
 [33 87 67 24]
 [81 24 56 40]
 [86 99 54 64]]
[[33 33 81 86]
 [52 87 24 99]
 [41 67 56 54]
 [94 24 40 64]]


In [68]:
# Guess the output
print(b[2,3])
print(b[0,0])


40
33


In [69]:
b[0:3,1],b[:,1]

(array([52, 87, 24]), array([52, 87, 24, 99]))

In [ ]:
b[1:3,:]

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [71]:
dates = pd.date_range('20140101',periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [73]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
print df
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

                   A         B         C         D
2014-01-01 -0.941027  0.572660  1.229962 -0.866317
2014-01-02  0.907026 -1.980164 -0.452785 -0.751228
2014-01-03  0.213691 -0.241337 -1.105002  0.217081
2014-01-04  0.614094 -1.416088 -0.790523 -1.542804
2014-01-05  0.309167 -0.243440  0.654247  0.460685
2014-01-06  0.285072 -0.590691  1.170869 -0.960233


Index([u'A', u'B', u'C', u'D'], dtype='object')

In [75]:
# Index, columns, underlying numpy data
print df.T
df

   2014-01-01  2014-01-02  2014-01-03  2014-01-04  2014-01-05  2014-01-06
A   -0.941027    0.907026    0.213691    0.614094    0.309167    0.285072
B    0.572660   -1.980164   -0.241337   -1.416088   -0.243440   -0.590691
C    1.229962   -0.452785   -1.105002   -0.790523    0.654247    1.170869
D   -0.866317   -0.751228    0.217081   -1.542804    0.460685   -0.960233


A         B         C         D
2014-01-01 -0.941027  0.572660  1.229962 -0.866317
2014-01-02  0.907026 -1.980164 -0.452785 -0.751228
2014-01-03  0.213691 -0.241337 -1.105002  0.217081
2014-01-04  0.614094 -1.416088 -0.790523 -1.542804
2014-01-05  0.309167 -0.243440  0.654247  0.460685
2014-01-06  0.285072 -0.590691  1.170869 -0.960233

In [80]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

A          B  C  D    E
0  1 2013-01-02  1  3  foo
1  1 2013-01-02  1  3  foo
2  1 2013-01-02  1  3  foo
3  1 2013-01-02  1  3  foo

In [ ]:
# With specific dtypes
df2.dtypes

#### Viewing Data

In [81]:
df.head()

A         B         C         D
2014-01-01 -0.941027  0.572660  1.229962 -0.866317
2014-01-02  0.907026 -1.980164 -0.452785 -0.751228
2014-01-03  0.213691 -0.241337 -1.105002  0.217081
2014-01-04  0.614094 -1.416088 -0.790523 -1.542804
2014-01-05  0.309167 -0.243440  0.654247  0.460685

In [82]:
df.tail()

A         B         C         D
2014-01-02  0.907026 -1.980164 -0.452785 -0.751228
2014-01-03  0.213691 -0.241337 -1.105002  0.217081
2014-01-04  0.614094 -1.416088 -0.790523 -1.542804
2014-01-05  0.309167 -0.243440  0.654247  0.460685
2014-01-06  0.285072 -0.590691  1.170869 -0.960233

In [ ]:
df.index

In [83]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.231337 -0.649843  0.117795 -0.573803
std    0.630357  0.915089  1.027569  0.761708
min   -0.941027 -1.980164 -1.105002 -1.542804
25%    0.231536 -1.209738 -0.706088 -0.936754
50%    0.297119 -0.417065  0.100731 -0.808773
75%    0.537862 -0.241863  1.041713 -0.024996
max    0.907026  0.572660  1.229962  0.460685

In [88]:
a = df.sort_values(by='B')
b = df
a is b

False

### Selection

In [90]:
df['A']

2014-01-01   -0.941027
2014-01-02    0.907026
2014-01-03    0.213691
2014-01-04    0.614094
2014-01-05    0.309167
2014-01-06    0.285072
Freq: D, Name: A, dtype: float64

In [96]:
df[3:4]

A         B         C         D
2014-01-04  0.614094 -1.416088 -0.790523 -1.542804

In [99]:
# By label
df.loc['20140101']

A   -0.941027
B    0.572660
C    1.229962
D   -0.866317
Name: 2014-01-01 00:00:00, dtype: float64

In [ ]:
# multi-axis by label
df.loc[:,['A','B']]

In [100]:
# Date Range
df.loc['20140102':'20140104',['B']]

B
2014-01-02 -1.980164
2014-01-03 -0.241337
2014-01-04 -1.416088

In [101]:
# Fast access to scalar
df.at[dates[1],'B']

-1.9801636572627592

In [104]:
# iloc provides integer locations similar to np style
df.iloc[]

A    0.907026
B   -1.980164
C   -0.452785
D   -0.751228
Name: 2014-01-02 00:00:00, dtype: float64

### Boolean Indexing

In [ ]:
df[df.A < 0] # Basically a 'where' operation

### Setting

In [110]:
df_posA = df.copy() # Without "copy" it would act on the dataset
print df_posA is df
df_posA[df_posA.A < 0]

False


A        B         C         D
2014-01-01 -0.941027  0.57266  1.229962 -0.866317

In [ ]:
df_posA

In [4]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [10]:
s1

2014-01-02    1
2014-01-03    2
2014-01-04    3
2014-01-05    4
2014-01-06    5
2014-01-07    6
Freq: D, dtype: int64

In [11]:
df['F'] = s1

In [12]:
df

A         B         C         D   F
2014-01-01 -0.322611  0.555363  0.038721  1.243797 NaN
2014-01-02  0.564839  0.339668  0.464357  0.069618   1
2014-01-03  1.037115  0.068227  1.217932 -0.539462   2
2014-01-04  0.827701 -0.731186  1.075909  1.042433   3
2014-01-05  1.324919 -3.743155 -1.500024  0.040583   4
2014-01-06 -0.080801  0.212183 -1.141660  0.528234   5

### Missing Data

In [113]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])
print df1

                   A         B         C         D   E
2014-01-01 -0.941027  0.572660  1.229962 -0.866317 NaN
2014-01-02  0.907026 -1.980164 -0.452785 -0.751228 NaN
2014-01-03  0.213691 -0.241337 -1.105002  0.217081 NaN
2014-01-04  0.614094 -1.416088 -0.790523 -1.542804 NaN


In [114]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [115]:
df1

A         B         C         D   E
2014-01-01 -0.941027  0.572660  1.229962 -0.866317   1
2014-01-02  0.907026 -1.980164 -0.452785 -0.751228   1
2014-01-03  0.213691 -0.241337 -1.105002  0.217081 NaN
2014-01-04  0.614094 -1.416088 -0.790523 -1.542804 NaN

In [116]:
# find where values are null
pd.isnull(df1)

A      B      C      D      E
2014-01-01  False  False  False  False  False
2014-01-02  False  False  False  False  False
2014-01-03  False  False  False  False   True
2014-01-04  False  False  False  False   True

### Operations

In [18]:
df.describe()

A         B         C         D         F
count  6.000000  6.000000  6.000000  6.000000  5.000000
mean   0.558527 -0.549817  0.025872  0.397534  3.000000
std    0.644056  1.625148  1.132034  0.672613  1.581139
min   -0.322611 -3.743155 -1.500024 -0.539462  1.000000
25%    0.080609 -0.531333 -0.846565  0.047842  2.000000
50%    0.696270  0.140205  0.251539  0.298926  3.000000
75%    0.984762  0.307797  0.923021  0.913883  4.000000
max    1.324919  0.555363  1.217932  1.243797  5.000000

In [19]:
df.mean(),df.mean(1) # Operation on two different axes

(A    0.558527
 B   -0.549817
 C    0.025872
 D    0.397534
 F    3.000000
 dtype: float64, 2014-01-01    0.378818
 2014-01-02    0.487697
 2014-01-03    0.756762
 2014-01-04    1.042971
 2014-01-05    0.024464
 2014-01-06    0.903591
 Freq: D, dtype: float64)

### Applying functions

In [20]:
df

A         B         C         D   F
2014-01-01 -0.322611  0.555363  0.038721  1.243797 NaN
2014-01-02  0.564839  0.339668  0.464357  0.069618   1
2014-01-03  1.037115  0.068227  1.217932 -0.539462   2
2014-01-04  0.827701 -0.731186  1.075909  1.042433   3
2014-01-05  1.324919 -3.743155 -1.500024  0.040583   4
2014-01-06 -0.080801  0.212183 -1.141660  0.528234   5

In [21]:
df.apply(np.cumsum)

A         B         C         D   F
2014-01-01 -0.322611  0.555363  0.038721  1.243797 NaN
2014-01-02  0.242229  0.895032  0.503078  1.313416   1
2014-01-03  1.279343  0.963258  1.721010  0.773953   3
2014-01-04  2.107045  0.232072  2.796919  1.816386   6
2014-01-05  3.431964 -3.511083  1.296894  1.856969  10
2014-01-06  3.351162 -3.298900  0.155234  2.385203  15

In [22]:
df.apply(lambda x: x.max() - x.min())

A    1.647530
B    4.298518
C    2.717956
D    1.783260
F    4.000000
dtype: float64

In [24]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

### Merge

In [26]:
np.random.randn(10,4)

array([[ 0.64707008,  0.06868756,  0.03396235, -0.59188989],
       [-0.64918839, -0.86186559, -0.12002715,  0.16246283],
       [-0.32728268, -1.90025805,  1.23873598, -0.76512758],
       [-0.44823202,  0.18844173,  1.4650924 ,  0.93016674],
       [ 0.46791308,  0.6197841 ,  0.606405  ,  0.65988749],
       [ 0.16240021, -1.06762815, -0.95700581,  0.94569329],
       [ 1.07544262,  0.40266274, -2.25176222, -1.32012351],
       [-1.02483136,  1.28550035, -1.4679147 ,  0.66737193],
       [-0.26680904,  0.35663339,  1.27343439, -0.79247446],
       [ 0.79097921, -0.60430802,  1.06141427, -0.83200708]])

In [36]:
#Concatenating pandas objects together
df =pd.DataFrame(np.random.randn(10,4))
df

0         1         2         3
0 -0.013153  0.514413  0.038994 -0.310020
1  0.037978  0.865428  0.092591  0.138314
2 -1.283542  1.821704  0.070445 -1.149399
3 -0.744688  0.713138  0.874457  0.851952
4 -0.900292  0.060578  1.255729 -1.874542
5 -0.202144 -0.828999  0.395968  0.411353
6 -0.636029 -0.875609 -1.201829 -1.212089
7 -1.107678  0.318552  0.402924  0.583644
8 -0.369238 -0.003418  0.710400  0.247617
9 -0.618139 -0.863911  1.625423 -1.087351

In [39]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

[          0         1         2         3
 0 -0.013153  0.514413  0.038994 -0.310020
 1  0.037978  0.865428  0.092591  0.138314
 2 -1.283542  1.821704  0.070445 -1.149399,
           0         1         2         3
 3 -0.744688  0.713138  0.874457  0.851952
 4 -0.900292  0.060578  1.255729 -1.874542
 5 -0.202144 -0.828999  0.395968  0.411353
 6 -0.636029 -0.875609 -1.201829 -1.212089,
           0         1         2         3
 7 -1.107678  0.318552  0.402924  0.583644
 8 -0.369238 -0.003418  0.710400  0.247617
 9 -0.618139 -0.863911  1.625423 -1.087351]

In [40]:
pd.concat(pieces)

0         1         2         3
0 -0.013153  0.514413  0.038994 -0.310020
1  0.037978  0.865428  0.092591  0.138314
2 -1.283542  1.821704  0.070445 -1.149399
3 -0.744688  0.713138  0.874457  0.851952
4 -0.900292  0.060578  1.255729 -1.874542
5 -0.202144 -0.828999  0.395968  0.411353
6 -0.636029 -0.875609 -1.201829 -1.212089
7 -1.107678  0.318552  0.402924  0.583644
8 -0.369238 -0.003418  0.710400  0.247617
9 -0.618139 -0.863911  1.625423 -1.087351

In [ ]:
# Also can "Join" and "Append"
df

### Grouping


In [41]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [42]:
df

A      B         C         D
0  foo    one  0.994904 -1.081762
1  bar    one -1.383157  0.920964
2  foo    two  1.346462 -0.416920
3  bar  three -0.589810  0.514681
4  foo    two -1.949785  0.268566
5  bar    two  1.840848  0.536430
6  foo    one  2.243927  1.113688
7  foo  three -2.646414 -0.248021

In [43]:
df.groupby(['A','B']).sum()

C         D
A   B                        
bar one   -1.383157  0.920964
    three -0.589810  0.514681
    two    1.840848  0.536430
foo one    3.238831  0.031925
    three -2.646414 -0.248021
    two   -0.603324 -0.148355

### Reshaping

In [ ]:
# You can also stack or unstack levels

In [44]:
a = df.groupby(['A','B']).sum()

In [45]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

C                             D                    
B         one     three       two       one     three       two
A                                                              
bar -1.383157 -0.589810  1.840848  0.920964  0.514681  0.536430
foo  1.619415 -2.646414 -0.301662  0.015963 -0.248021 -0.074177

### Time Series


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [ ]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [ ]:
ts

In [ ]:
# Built in resampling
ts.resample('1Min').mean() # Resample secondly to 1Minutely

In [ ]:
# Many additional time series features
ts. #use tab

### Plotting


In [ ]:
ts.plot()

In [ ]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [ ]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [ ]:
# Pandas plot function will print with labels as default

In [ ]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

#### The benefits of open source:

Let's look under x's in plt modules

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/10min.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas