# Project 3

In this project, you will perform a logistic regression on the admissions data we've been working with in projects 1 and 2.

In [11]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm
import pylab as pl
import numpy as np


Comment: Remember in your project unit 2 that you found some missing values? We have to drop them for the analysis.

In [10]:
df_raw = pd.read_csv("../assets/admissions.csv")
df = df_raw.dropna() 
print df.head()

   admit  gre   gpa  prestige
0      0  380  3.61         3
1      1  660  3.67         3
2      1  800  4.00         1
3      1  640  3.19         4
4      0  520  2.93         4


In [12]:
print df.isnull().sum()  #No more nulls

admit       0
gre         0
gpa         0
prestige    0
dtype: int64


## Part 1. Frequency Tables

What is a frequency table? You are basically counting the number of observations on unique columns of a DataFrame.

What does that mean? In our case, we have an admit column and a prestige column. Both are categorical variables as you have verified in previous unit projects. For each admit category AND each prestige category, you want to tabulate the number of observations for each combination of categories. For example, your result should look like:


| prestige | 1.0 | 2.0 | 3.0 | 4.0 |
|----------|-----|-----|-----|-----|
| admit    |     |     |     |     |
| 0        | 28  | 95  | 93  | 55  |
| 1        | 33  | 53  | 28  | 12  |


How do you do this? Use the Pandas **crosstab** function. Go the Pandas documentation and find that function. There is an 'index' argument and a 'column' argument. The index argument says "values to group-by in the rows". The rows refer to the tabulated table rows (admit in the example above). Because we want admit to be the rows, we can pass in our admit column of our df DataFrame like this: df['admit']. The crosstab function will know to group all the 1 observations together and the 0 observations together. Then, in the column argument to crosstab, you can pass in your prestige data. Crosstab will take the groups of admit = 1 and 0 and further segment those groups by prestige levels and just do a simple count of how many obeservations are in each.

Play around with passing in different columns to the crosstab function and see what happens. You can even pass a list of two columns (note the documentation says you can do that if you look at the index/column argument). Can you explain what is going on?
#### 1. Let's create a frequency table of our variables

In [ ]:
# frequency table for prestige and whether or not someone was admitted


For the index argument of crosstab, pass in prestige and admit columns in a list and then pass in the gpa column of df into the column argument of crosstab. What happens?

In [5]:
#Do that here

## Part 2. Return of dummy variables

#### 2.1 Create class or dummy variables for prestige 

You guys know what function to use here right? Call the dummy frame 'dummy_ranks' to work with starter code in latter cells. Also, use the prefix argument and pass in 'prestige' to it.

DO NOT DROP ONE OF THE COLUMNS JUST YET

In [6]:
#Do the dummy thing in here!

#### 2.2 When modeling our class variables, how many of the dummy_ranks columns do we need? 



Answer: 

## Part 3. Hand calculating odds ratios

Develop your intuition about expected outcomes by hand calculating odds ratios.

In the cell below, the .ix DataFrame accessor will attempt to use the index LABEL to retrieve elements and if
it doesn't find any matching labels, it just uses the position in the frame. In the below code, .ix[:,'prestige_1':] accesses the rows by ':' which means 'grab all rows' and can be used for labels OR positions. The 'prestige_1:' means grab all columns starting at 'prestige_1' onwards. In the case of dummy_ranks, that's all of the columns hence the .ix accessor just grabs the whole DataFrame as is (no subsetting happens here).

In [ ]:
cols_to_keep = ['admit', 'gre', 'gpa']
handCalc = df[cols_to_keep].join(dummy_ranks.ix[:, 'prestige_1':])
print handCalc.head()

#### 3.0 Just as you've done, create a crosstab for admit in the rows of the crosstab and prestige_1.0 in the columns of the crosstab


In [7]:
#Run crosstab here

Interpret: 

#### 3.1 Use the cross tab above to calculate the odds of being admitted to grad school if you attended a #1 ranked 

Recall Odds: Odds represent $$\frac{P(\text{something happening})}{P(\text{something not happening})}$$

What the question asks is tocalculate $$\frac{P(\text{admit}\hspace{2mm}|\hspace{2mm}\text{attended rank-1 school})}{P(\text{not admit}\hspace{2mm}|\hspace{2mm}\text{attended rank-1 school})}$$

Because we are concerned with probabilities GIVEN that an observation fell into the 'rank-1 school' = 1 bucket, you should take  a look at the column of the crosstab that has 'prestige_1.0' = 1

How do you calculate probabilities within columns?

#### 3.2 Now calculate the odds of admission if you did not attend a #1 ranked college

#### 3.3 Calculate the odds ratio (OR). 

Basically take the number you calculated in 3.1 and 3.2 and divide.

#### 3.4 Write this finding in a sentence: 

How do you interpret this?

Answer: 

#### 3.5 Do the same as above with prestige_4.0 columns.

Print the crosstab below:

#### 3.6 Calculate the Odds Ratio of admission given attended prestige_4.0 school to not attended prestige_4.0 school.

#### 3.7 Write this finding in a sentence. Also, compare to the prestige_1.0 odds ratio

Answer:

## Part 4. Analysis

Use statsmodels and Scikit Learn to do a Logistic Regression of all the co-variates.

Background Info:

Remember Starter Code for Lesson 6? There we used a package called statsmodels to do a regression analysis. You can also use Statsmodels to do a Logistic Regression. But you can also do a Logistic Regression in Scikit Learn. Why do we need both?

1. Statsmodels - Great when you want quick and easy statistical interpretation of your model. The P-values are output as part of the fitting process.

2. Scikit Learn - Great when you want full-blown modelling and Machine Learning and Optimization tools. Think GridSearchCV or Cross Validation

It's actually a great idea to use both of them as you are doing an analysis. You can gain some insight into which variables are statistically significant and hence worthwhile keeping in a model by using statsmodels. If your variables are statistically significant, then you have more confidence that your model will generalize and a relationship wasn't found by fitting random noise in your particular sample.

In [14]:

# create a clean data frame for the regression
cols_to_keep = ['admit', 'gre', 'gpa']
data = df[cols_to_keep].join(dummy_ranks.ix[:, 'prestige_2':])
print data.head()

   admit  gre   gpa  prestige_2.0  prestige_3.0  prestige_4.0
0      0  380  3.61             0             1             0
1      1  660  3.67             0             1             0
2      1  800  4.00             0             0             0
3      1  640  3.19             0             0             1
4      0  520  2.93             0             0             1


We're going to add a constant term for our Logistic Regression. The statsmodels function we're going to be using requires that intercepts/constants are specified explicitly.

In [15]:
# manually add the intercept
data['intercept'] = 1.0

Think about why adding an intercept column of all 1's actually represents an intercept term in the regression?

Ans:

#### 4.1 Set the covariates to a variable called train_cols

This is basically your X.

#### 4.2 Fit the model

The documentation is a little bit tricky. It can be found here: http://statsmodels.sourceforge.net/0.6.0/generated/statsmodels.discrete.discrete_model.Logit.html

By the way, notice how we imported statsmodels.api in the statement "import statsmodels.api as sm" at the top of the project. What does that mean? It clearly looks different from the module namespace for Logit (statsmodels.discrete.discrete_model.Logit) in the Logit docs. This helps explain what is going on: http://statsmodels.sourceforge.net/devel/importpaths.html

Basically, the fit process involves 2 steps. If you have problems here, please Slack me ASAP

1. Create a Logit object passing in the correct arguments. "endog" is the dependent variable according to the documentation while "exog" must be the independent variables.

2. Fit the model. Does the fit model need any arguments? Check out the documentation for the fit method.

#### 4.3 Print the summary results

Please interpret the results. Be as thorough as you can. In your answer, talk about things such as:

1. What are the significant predictors?

2. What do the coefficients mean?

3. How do you explain the dummy-variable coefficients in particular. Do the numbers make sense?

Answer:

#### 4.4 Calculate the change in odds of the coeffiencents and their 95% CI intervals

Recall that the Logistic Regression model is the following:

$$P(y = 1 | X) = \frac{1}{1 + e^{-(\beta_0 + \beta_1X_1 + ... + \beta_pX_p)}}$$ 

Rearranging this equation gives us the odds (shortening $P(y=1|X)$ to P):

$$e^{\beta_0 + \beta_1X_1 + ... + \beta_pX_p} = \frac{P}{1-P}$$

Now, what happens to the odds when we increase $X_1$ by one unit:

$$e^{\beta_0 + \beta_1(X_1 + 1) + ... + \beta_pX_p} = e^{\beta_1}e^{\beta_0 + \beta_1X_1 + ... + \beta_pX_p} = \frac{P}{1-P}e^{\beta_1}$$

The takeaway is that when we increase $X_i$ by one unit, the *odds* change by a factor of $e^{\beta_i}$

1. Calculate the change in odds associated by a one-unit increase in **each** of the variables

2. From the model, extract the confidence intervals associated with **each** of the variables.

In [ ]:
#Do part 1 here

In [ ]:
#Do part 2 here

What does the lower end of the confidence interval mean? The upper end? Please interpret

Answer:

#### 4.5 Interpret the odds change associated with Prestige_2.0

That is, using the numbers you just found above, what do they mean?

Answer: 

#### 4.6 Interpret the odds change of GPA

Answer: 

## Part 5: Model Fit using Scikit Learn

We started this in class on Monday 9/19. You shouldn't have much problem with this because we've done it many times now. If you run into trouble please Slack me ASAP.


#### 5.1 Fit the model

In [ ]:
#Fit here

#### 5.2 Print out the coefficients

#### 5.3 Compare to your Statsmodels Results

Answer:

## Part 5: Predicted probablities


**NOTE** -- Think of the below as a way to generate a test set from the data.

As a way of evaluating our classifier, we're going to recreate the dataset with every logical combination of input values. This will allow us to see how the predicted probability of admission increases/decreases across different variables. First we're going to generate the combinations using a helper function called cartesian (above).

We're going to use np.linspace to create a range of values for "gre" and "gpa". This creates a range of linearly spaced values from a specified min and maximum value--in our case just the min/max observed values.

In [8]:
def cartesian(arrays, out=None):
    """
    Generate a cartesian product of input arrays.
    Parameters
    ----------
    arrays : list of array-like
        1-D arrays to form the cartesian product of.
    out : ndarray
        Array to place the cartesian product in.
    Returns
    -------
    out : ndarray
        2-D array of shape (M, len(arrays)) containing cartesian products
        formed of input arrays.
    Examples
    --------
    >>> cartesian(([1, 2, 3], [4, 5], [6, 7]))
    array([[1, 4, 6],
           [1, 4, 7],
           [1, 5, 6],
           [1, 5, 7],
           [2, 4, 6],
           [2, 4, 7],
           [2, 5, 6],
           [2, 5, 7],
           [3, 4, 6],
           [3, 4, 7],
           [3, 5, 6],
           [3, 5, 7]])
    """

    arrays = [np.asarray(x) for x in arrays]
    dtype = arrays[0].dtype

    n = np.prod([x.size for x in arrays])
    if out is None:
        out = np.zeros([n, len(arrays)], dtype=dtype)

    m = n / arrays[0].size
    out[:,0] = np.repeat(arrays[0], m)
    if arrays[1:]:
        cartesian(arrays[1:], out=out[0:m,1:])
        for j in xrange(1, arrays[0].size):
            out[j*m:(j+1)*m,1:] = out[0:m,1:]
    return out

In [16]:
# instead of generating all possible values of GRE and GPA, we're going
# to use an evenly spaced range of 10 values from the min to the max 
gres = np.linspace(data['gre'].min(), data['gre'].max(), 10)
print gres
# array([ 220.        ,  284.44444444,  348.88888889,  413.33333333,
#         477.77777778,  542.22222222,  606.66666667,  671.11111111,
#         735.55555556,  800.        ])
gpas = np.linspace(data['gpa'].min(), data['gpa'].max(), 10)
print gpas
# array([ 2.26      ,  2.45333333,  2.64666667,  2.84      ,  3.03333333,
#         3.22666667,  3.42      ,  3.61333333,  3.80666667,  4.        ])


# enumerate all possibilities
combos = pd.DataFrame(cartesian([gres, gpas, [1, 2, 3, 4], [1.]]))

[ 220.          284.44444444  348.88888889  413.33333333  477.77777778
  542.22222222  606.66666667  671.11111111  735.55555556  800.        ]
[ 2.26        2.45333333  2.64666667  2.84        3.03333333  3.22666667
  3.42        3.61333333  3.80666667  4.        ]


#### 5.1 Recreate the dummy variables

Create the dummy column

In [ ]:
# recreate the dummy variables

# keep only what we need for making predictions


#### 5.2 Make probability predictions on the enumerated dataset

Do this on your **Statsmodels** fit. Use the predict function: http://statsmodels.sourceforge.net/0.6.0/generated/statsmodels.discrete.discrete_model.Logit.predict.html#statsmodels.discrete.discrete_model.Logit.predict

Note the last argument is called "linear" and it is optional with a default set to False. The docs say "Else, returns the value of the cdf at the linear predictor." The value of the CDF is basically the probability

#### 5.3 Interpret findings for the last 4 observations

Answer: 

## Bonus

Plot the probability of being admitted into graduate school, stratified by GPA and GRE score.